'use client';
import { useState } from 'react';
import { ResponsiveContainer, CartesianGrid, LineChart, Line, XAxis, YAxis, Tooltip } from 'recharts';
import { Button } from '@/components/ui/button';
import type { Ga4Data } from '@/hooks/use-ga4';

export function Ga4Performance({ data, onSettings }: { data?: Ga4Data; onSettings: () => void }) {
  const [days, setDays] = useState('28'), [start, setStart] = useState(''), [end, setEnd] = useState('');
  const report = data && !data.loading && !data.error ? data.report : null;
  return <>
    <div className="flex items-center justify-between gap-3"><div><h2 className="text-sm font-bold">AI 추천 유입 · GA4 방문 분석</h2><p className="mt-1 text-[10px] text-[#8f8b98]">GA4에서 AI 서비스의 referral 출처로 구분된 세션만 집계합니다.</p></div><span className="text-2xl font-bold">{report ? report.ai.sessions.toLocaleString() : '—'}</span></div>
    <form className="mt-4 flex flex-wrap items-end gap-2" onSubmit={event => { event.preventDefault(); if (!data) return; data.setRange(days === 'custom' ? new URLSearchParams({ startDate: start, endDate: end }).toString() : `days=${days}`); data.reload(); }}>
      <label className="text-[10px] text-[#777381]">조회 기간<select className="mt-1 block rounded-lg border border-[#e8e6ee] bg-white p-2 text-xs" value={days} onChange={event => setDays(event.target.value)}><option value="7">최근 7일</option><option value="28">최근 28일</option><option value="90">최근 90일</option><option value="custom">직접 선택</option></select></label>
      {days === 'custom' && <><label className="text-[10px]">시작일<input required type="date" value={start} onChange={event => setStart(event.target.value)} className="mt-1 block rounded-lg border p-2 text-xs" /></label><label className="text-[10px]">종료일<input required type="date" value={end} onChange={event => setEnd(event.target.value)} className="mt-1 block rounded-lg border p-2 text-xs" /></label></>}
      <Button type="submit" size="sm" variant="outline" disabled={data?.loading || !data?.status?.connected}>조회·새로고침</Button>
    </form>
    {report ? <>
      <p className="mt-3 text-[10px] leading-5 text-[#8f8b98]">{report.startDate} ~ {report.endDate} · GA4 속성 시간대 {report.timezone}<br />조회 시각 {new Date(report.fetchedAt).toLocaleString('ko-KR', { timeZone: 'Asia/Seoul' })} KST</p>
      <div className="mt-4 grid grid-cols-3 gap-2">{[['전체 세션', report.totals.sessions], ['활성 사용자', report.totals.activeUsers], ['주요 이벤트', report.totals.keyEvents]].map(([label, value]) => <div key={label} className="rounded-xl bg-[#f7f5ff] p-3"><p className="text-[10px] text-[#777381]">{label}</p><strong className="mt-1 block text-lg text-[#5d49d2]">{Number(value).toLocaleString()}</strong></div>)}</div>
      <h3 className="mt-5 text-[11px] font-bold">확인 가능한 AI 추천 세션 추이</h3><div className="mt-3 h-40" role="img" aria-label={`${report.startDate}부터 ${report.endDate}까지 AI 추천 세션 ${report.ai.sessions}회`}><ResponsiveContainer width="100%" height="100%"><LineChart data={report.daily}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="date" tickFormatter={date => String(date).slice(5)} tick={{ fontSize: 9 }} minTickGap={30} /><YAxis allowDecimals={false} width={30} tick={{ fontSize: 9 }} /><Tooltip /><Line type="linear" dataKey="aiSessions" name="AI 추천 세션" stroke="#6957e8" dot={false} strokeWidth={2} /></LineChart></ResponsiveContainer></div>
      <div className="mt-4 grid gap-5 sm:grid-cols-2"><div><h3 className="text-[10px] font-bold">유입 AI</h3>{report.ai.sources.length ? report.ai.sources.map(source => <div key={source.name} className="mt-2 flex justify-between gap-2 text-xs"><span>{source.name}</span><strong>{source.sessions.toLocaleString()}회</strong></div>) : <p className="mt-2 text-xs text-[#8f8b98]">선택 기간에 확인 가능한 AI referral 세션이 없습니다.</p>}</div><div><h3 className="text-[10px] font-bold">AI 방문 상위 페이지</h3>{report.ai.pages.length ? report.ai.pages.map(page => <div key={page.path} className="mt-2 flex justify-between gap-2 text-xs"><span className="break-all">{page.path}</span><strong className="shrink-0">{page.sessions.toLocaleString()}회</strong></div>) : <p className="mt-2 text-xs text-[#8f8b98]">확인된 페이지 없음</p>}</div></div>
      <details className="mt-5 text-xs"><summary className="cursor-pointer font-semibold text-[#6957e8]">전체 유입 출처·이벤트·일별 수치 보기</summary><div className="mt-3 space-y-4"><div className="max-h-48 overflow-auto"><table className="w-full text-left text-[10px]"><caption className="mb-2 text-left font-bold">전체 유입 출처 상위 20개</caption><thead><tr><th>출처 / 매체</th><th className="text-right">세션</th></tr></thead><tbody>{report.sources.map(source => <tr key={`${source.source}/${source.medium}`}><td className="break-all py-1">{source.source} / {source.medium}</td><td className="text-right">{source.sessions.toLocaleString()}</td></tr>)}</tbody></table></div><div className="max-h-48 overflow-auto"><table className="w-full text-left text-[10px]"><caption className="mb-2 text-left font-bold">발생 이벤트 상위 20개 · 예약 환자 수가 아님</caption><thead><tr><th>이벤트 이름</th><th className="text-right">발생 횟수</th></tr></thead><tbody>{report.events.map((event, index) => <tr key={`${event.name}-${index}`}><td className="py-1">{event.name}</td><td className="text-right">{event.count.toLocaleString()}</td></tr>)}</tbody></table></div><div className="max-h-48 overflow-auto"><table className="w-full text-left text-[10px]"><caption className="mb-2 text-left font-bold">일별 세션</caption><thead><tr><th>날짜</th><th>전체</th><th>AI 추천</th></tr></thead><tbody>{report.daily.map(day => <tr key={day.date}><td className="py-1">{day.date}</td><td>{day.sessions.toLocaleString()}</td><td>{day.aiSessions.toLocaleString()}</td></tr>)}</tbody></table></div></div></details>
      {report.warnings.map(warning => <p key={warning} className="mt-3 text-xs leading-5 text-[#a56225]">{warning}</p>)}
    </> : <div className="py-6"><p role="status" className="text-xs leading-6 text-[#8f8b98]">{data?.loading ? 'GA4 연결·실제 보고서를 확인하고 있습니다…' : data?.error || (data?.status?.needsReconnect ? 'Google 권한을 다시 승인해 주세요.' : 'Google 인증 설정과 읽기 권한 승인 후 실제 수치를 조회할 수 있습니다. 연결 전에는 숫자와 그래프를 만들지 않습니다.')}</p><Button size="sm" variant="outline" className="mt-3" onClick={onSettings}>GA4 연결 안내</Button></div>}
    <p className="mt-5 text-[10px] leading-5 text-[#8f8b98]">AI 추천 유입은 추적 가능한 일부 방문입니다. 출처가 사라진 방문·앱 내 답변 노출은 포함되지 않으며, 이 수치만으로 콘텐츠의 효과를 단정하지 않습니다. 봇 방문·환자 수·예약 완료와는 다릅니다. 주요 이벤트는 GA4에 지정된 이벤트의 집계입니다.</p>
  </>;
}
