'use client';

import type { ReactNode } from 'react';
import { ArrowLeft, FileDown, ShieldCheck } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Heading } from '@/components/dashboard-primitives';
import audit from '@/data/goldman-audit.json';
import { goldmanFindings } from '@/data/goldman-findings';
import { searchMetrics, type SearchImport } from '@/lib/search-console';

function Sheet({ title, page, children }: { title: string; page: number; children: ReactNode }) {
  return <section className="report-sheet relative border border-[#e8e6ee] bg-white p-10 text-[#20202a]"><header className="mb-6 flex items-center justify-between border-b border-[#e8e6ee] pb-4"><h2 className="text-xl font-bold">{title}</h2><span className="text-xs font-semibold text-[#6957e8]">MediAnswer · 골드만</span></header>{children}<footer className="absolute inset-x-10 bottom-5 flex justify-between border-t border-[#e8e6ee] pt-3 text-[10px] text-[#8f8b98]"><span>공개 홈페이지 진단 {audit.checkedDate} · AI 성과 실측 아님</span><span>{page} / 5</span></footer></section>;
}

export function GoldmanReport({ report, loading, error, onBack }: { report: SearchImport | null; loading: boolean; error: string; onBack: () => void }) {
  const ready = !loading && !error && report;
  const metrics = searchMetrics(ready ? report.rows : []);
  async function printReport() { await document.fonts.ready; window.print(); }
  return <div className="report-print-root">
    <div className="report-no-print"><Heading eyebrow="Public Website Diagnosis" title="골드만 AEO 재진단 보고서" description="현재 홈페이지 관찰과 저장된 검색 자료를 구분했습니다. 인쇄 창에서 PDF로 저장할 수 있습니다." action={<div className="flex gap-2"><Button variant="outline" onClick={onBack}><ArrowLeft className="size-4" />대시보드</Button><Button className="bg-[#6957e8] hover:bg-[#5845d5]" onClick={printReport}><FileDown className="size-4" />PDF로 저장·인쇄</Button></div>} /></div>
    <div className="overflow-x-auto"><div className="report-document space-y-7 pb-10">
      <Sheet title="01. 진단 요약과 실제 데이터 범위" page={1}><div className="rounded-2xl bg-[#f7f5ff] p-6"><p className="text-sm font-bold text-[#6957e8]">https://www.gold-man.com/ · {audit.checkedDate}</p><h1 className="mt-3 text-[30px] font-bold">기본 구성은 있습니다. 정보의 일관성부터 보완하세요.</h1><p className="mt-4 text-base leading-7 text-[#625e6c]">{audit.summary}</p></div><div className="mt-5 grid grid-cols-3 gap-4">{[['직접 확인한 HTML', `${audit.pages.length}개`], ['수집 설정 파일', `${audit.resources.length}개`], ['AI 언급·인용', '미측정']].map(([label, value]) => <div key={label} className="rounded-xl border border-[#e8e6ee] p-4"><div className="text-xs text-[#777381]">{label}</div><strong className="mt-2 block text-2xl">{value}</strong></div>)}</div><div className="mt-5 rounded-xl border border-[#e8e6ee] p-5"><h2 className="text-sm font-bold">Search Console 저장 자료 · 홈페이지 진단과 별도</h2><p className="mt-2 text-sm leading-6">{ready ? `${report.startDate} ~ ${report.endDate} · ${report.rows.length.toLocaleString()}개 ${report.dimension === 'query' ? '검색어' : '페이지'} · 클릭 ${metrics.clicks.toLocaleString()}회 · 노출 ${metrics.impressions.toLocaleString()}회 · 클릭률 ${metrics.ctr.toFixed(2)}%` : loading ? '저장 자료 확인 중' : error || '저장된 자료 없음'}</p><p className="mt-2 text-xs leading-5 text-[#8f8b98]">사용자 제공 CSV에 포함된 행의 합계이며 전체 검색 실적과 다를 수 있습니다. Google 계정 자동 연결이나 실제 AI 노출 측정을 의미하지 않습니다.</p></div><p className="mt-5 text-xs leading-6 text-[#777381]">{audit.scope}<br />{audit.method}</p></Sheet>
      {[goldmanFindings.slice(0, 2), goldmanFindings.slice(2)].map((group, index) => <Sheet key={index} title={index === 0 ? '02. 우선 검토: 비용과 치료 설명' : '03. 다음 실행: 지점 안내와 기존 문서'} page={index + 2}><div className="grid grid-cols-2 gap-6">{group.map(finding => <article key={finding.id} className="rounded-2xl border border-[#e8e6ee] p-6"><span className="text-xs font-bold text-[#6957e8]">{finding.priority}</span><h3 className="mt-3 text-xl font-bold leading-8">{finding.title}</h3><p className="mt-4 text-sm leading-7">{finding.observation}</p><p className="mt-3 text-sm leading-6 text-[#777381]">{finding.implication}</p><div className="mt-4 rounded-xl bg-[#f7f5ff] p-4 text-sm leading-6"><strong className="block text-[#6957e8]">권장 실행</strong>{finding.action}</div><p className="mt-3 text-xs text-[#777381]">담당: {finding.owner}</p><div className="mt-4 space-y-2">{finding.sources.map(source => <a key={source.url} href={source.url} target="_blank" rel="noreferrer" className="block break-all text-[10px] leading-4 text-[#6957e8]">{source.label} · {source.url}</a>)}</div></article>)}</div></Sheet>)}
      <Sheet title="04. 이전 관찰과 달라진 항목" page={4}><div className="space-y-4">{audit.rechecked.map(item => <article key={item.title} className="rounded-xl border border-[#cfe9df] bg-[#eff9f4] p-5"><h3 className="flex items-center gap-2 text-base font-bold text-[#247c5e]"><ShieldCheck className="size-4" />{item.title}</h3><p className="mt-2 text-xs leading-5 text-[#777381]">이전: {item.before}</p><p className="mt-2 text-sm leading-6">현재: {item.now}</p><a className="mt-2 block text-[10px] text-[#6957e8]" href={item.url} target="_blank" rel="noreferrer">{item.url}</a></article>)}</div><p className="mt-5 text-xs leading-6 text-[#777381]">확인된 변화가 메디앤서의 작업 때문에 발생했다고 단정하지 않습니다. 현재 공식 서버 응답을 다시 확인한 결과이며, 홈페이지 자체를 수정한 작업은 아닙니다.</p></Sheet>
      <Sheet title="05. 확인한 URL과 점검 한계" page={5}><div className="grid grid-cols-[minmax(0,1.9fr)_minmax(0,.8fr)] gap-6"><table className="w-full text-left text-xs"><thead><tr className="bg-[#f7f5ff]"><th className="px-2 py-1.5">표본 페이지</th><th>HTTP</th><th>설명 태그</th><th>대표 URL</th><th>JSON-LD 블록</th></tr></thead><tbody>{audit.pages.map(page => <tr key={page.url} className="border-b border-[#efedf3]"><td className="px-2 py-1.5"><a href={page.url} target="_blank" rel="noreferrer" className="text-[#6957e8]">{page.name}</a><div className="mt-0.5 text-[9px] text-[#8f8b98]">{page.url}</div></td><td>{page.status}</td><td>{page.description ? '있음' : '없음'}</td><td>{page.canonical ? '있음' : '없음'}</td><td>{page.structuredDataBlocks}</td></tr>)}</tbody></table><aside><h3 className="mb-3 text-sm font-bold">수집 설정</h3><div className="space-y-4">{audit.resources.map(source => <a key={source.url} href={source.url} target="_blank" rel="noreferrer" className="block text-[10px] text-[#6957e8]">{source.name} · HTTP {source.status}</a>)}</div><div className="mt-4 rounded-xl bg-[#faf9fc] p-4 text-xs leading-6 text-[#777381]">표본 응답에서 noindex 지시는 발견되지 않았습니다. 구조화 데이터의 존재와 HTTP 200 응답만으로 Google 색인·AI 인용·진료 내용의 정확성을 보증할 수는 없습니다. 동적 상세 화면, 전체 URL, 실제 계정 색인 상태 및 임상·광고 적합성은 추가 확인 대상입니다.</div></aside></div></Sheet>
    </div></div>
  </div>;
}
