'use client';

import { useState } from 'react';
import { BarChart3, Bot, CalendarDays, FileCheck2, FileDown, Globe2, Link2, MousePointerClick, Quote, RefreshCw, Search, Target } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Heading } from '@/components/dashboard-primitives';
import { searchMetrics, type SearchImport } from '@/lib/search-console';
import type { WorkspaceView } from '@/lib/workspace-navigation';
import audit from '@/data/goldman-audit.json';
import type { Ga4Data } from '@/hooks/use-ga4';
import { Ga4Performance } from '@/components/ga4-performance';

const panel = 'rounded-2xl border border-[#e8e6ee] bg-white p-5 sm:p-6';

export function GoldmanPerformance({ report, loading, error, onNavigate, ga4 }: { report: SearchImport | null; loading: boolean; error: string; onNavigate: (view: WorkspaceView) => void; ga4?: Ga4Data }) {
  const ga4Report = ga4 && !ga4.loading && !ga4.error ? ga4.report : null;
  const [metric, setMetric] = useState('전체');
  const ready = !loading && !error && report;
  const metrics = searchMetrics(ready ? report.rows : []);
  const top = [...(ready ? report.rows : [])].sort((a, b) => b.clicks - a.clicks).slice(0, 5);
  const maxClicks = Math.max(1, ...top.map(row => row.clicks));
  return <>
    <Heading eyebrow="AI Visibility Performance" title="골드만의 검색 현황과 AI 측정 준비 상태를 확인합니다" description="골드만 공식 홈페이지 재진단과 저장된 검색 자료를 함께 봅니다. 검색 실적과 AI 답변의 언급·인용은 다른 지표이며, 미측정 값을 성과로 표시하지 않습니다." action={<div className="flex flex-wrap gap-2"><Button className="bg-[#6957e8] hover:bg-[#5845d5]" onClick={() => onNavigate('report')}><FileDown className="size-4" />PDF 진단 보고서</Button><Button variant="outline" onClick={() => onNavigate('settings')}><Link2 className="size-4" />실측 데이터 연결</Button></div>} />
    <div className="mb-5 flex flex-col gap-3 rounded-2xl border border-[#e4dcaa] bg-[#fffdf2] p-4 sm:flex-row sm:items-center" role={error ? 'alert' : 'status'}>
      <div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-[#f6e9a8] text-[#7c6411]"><BarChart3 className="size-5" /></div>
      <div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Badge className="border border-[#d8c765] bg-[#fff7c9] text-[#6e590f]">{ready ? '검색 실측 자료' : '자료 확인'}</Badge><span className="text-xs font-bold text-[#5a4a16]">공개 홈페이지 재진단 {audit.checkedDate} · AI 답변 미측정</span></div><p className="mt-1 text-[11px] leading-5 text-[#766b43]">{loading ? '저장된 Search Console 자료를 확인하고 있습니다.' : error || (report ? `검색 자료 기간 ${report.startDate} ~ ${report.endDate} · ${report.rows.length.toLocaleString()}개 ${report.dimension === 'query' ? '검색어' : '페이지'} · CSV 저장 자료이며 Google 계정 자동 연결은 아닙니다.` : 'Search Console에 병원이 등록돼 있어도 메디앤서 연결은 별도입니다. 검색어 CSV를 저장해 주세요.')}</p></div>
      <Button size="sm" className="shrink-0 bg-[#2d2a21] text-white hover:bg-[#17150f]" onClick={() => onNavigate('command')}>재진단 결과 보기 <FileCheck2 className="size-3.5" /></Button>
    </div>
    <section className="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      {[
        { label: 'AI 브랜드 언급률', description: '정해진 질문의 답변에 골드만이 등장한 비율', icon: Quote, tone: 'bg-[#efecff] text-[#6957e8]' },
        { label: 'AI 노출 점유율', description: '비교 병원 전체 언급에서 골드만이 차지한 비중', icon: Target, tone: 'bg-[#e8f7f1] text-[#218462]' },
        { label: '공식 도메인 인용률', description: '답변에 gold-man.com 출처가 포함된 비율', icon: Globe2, tone: 'bg-[#fff1e6] text-[#d77832]' },
        { label: 'AI 추천 유입', description: 'AI 서비스에서 홈페이지로 온 확인 가능한 방문', icon: MousePointerClick, tone: 'bg-[#e8f2ff] text-[#397ac5]' },
      ].map(({ label, description, icon: Icon, tone }) => <article key={label} className="rounded-2xl border border-[#e8e6ee] bg-white p-5 shadow-[0_2px_10px_rgba(31,28,45,.025)]"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="text-xs font-semibold text-[#777381]">{label}</span><span className="rounded bg-[#f3f1f6] px-1.5 py-0.5 text-[8px] font-bold text-[#8b8793]" >{label === 'AI 추천 유입' && ga4Report ? 'GA4 실측' : '미측정'}</span></div><p className="mt-1 text-[9px] leading-4 text-[#9a96a3]">{description}</p></div><span className={`grid size-8 shrink-0 place-items-center rounded-lg ${tone}`}><Icon className="size-4" /></span></div><div className="mt-4 text-[30px] font-bold leading-none tracking-[-.04em]">{label === 'AI 추천 유입' && ga4Report ? ga4Report.ai.sessions.toLocaleString() : '—'}</div><div className="mt-3 text-[10px] font-medium text-[#777381]">{label === 'AI 추천 유입' && ga4Report ? `${ga4Report.startDate} ~ ${ga4Report.endDate} · 세션` : '수집 기능과 데이터 연결이 필요합니다'}</div></article>)}
    </section>
    <section className="mb-5 grid gap-4 xl:grid-cols-[minmax(0,1.7fr)_minmax(300px,.7fr)]">
      <div className={panel}><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2"><h2 className="text-sm font-bold">AI 노출 성과 추이</h2><Badge variant="outline" className="text-[8px] text-[#777381]">미측정</Badge></div><p className="mt-1 text-[10px] leading-4 text-[#8f8b98]">같은 질문·모델·검색 조건의 반복 측정이 필요합니다.</p></div><div className="flex flex-wrap gap-1 rounded-lg bg-[#f3f1f6] p-1">{['전체', '언급률', '점유율', '인용률'].map(value => <button key={value} onClick={() => setMetric(value)} aria-pressed={metric === value} className={`rounded-md px-2.5 py-1.5 text-[9px] font-bold ${metric === value ? 'bg-white text-[#5d49d2] shadow-sm' : 'text-[#8f8b98]'}`}>{value}</button>)}</div></div>
        <div className="mt-5 flex h-[310px] flex-col items-center justify-center rounded-xl border border-dashed border-[#e4def4] bg-[#fcfbff] px-6 text-center" aria-live="polite"><BarChart3 className="size-9 text-[#b1a7dd]" /><h3 className="mt-4 text-sm font-bold">{metric === '전체' ? 'AI 노출' : metric} 측정값이 아직 없습니다</h3><p className="mt-2 max-w-md text-xs leading-6 text-[#8f8b98]">검색 클릭이 있다는 사실만으로 AI가 병원을 추천했다고 판단하지 않습니다. 실제 답변 원문이 없는 기간에는 그래프를 그리지 않습니다.</p><Button variant="outline" size="sm" className="mt-4" onClick={() => onNavigate('monitor')}>측정 기준선 확인</Button></div>
        <div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-2 border-t border-[#f0eef4] pt-4 text-[9px] text-[#8e8a96]"><span className="inline-flex items-center gap-1.5"><CalendarDays className="size-3.5 text-[#6957e8]" />AI 측정 기간 없음</span><span>발행 전·후 비교 대기</span><span>유효 답변 미수집</span></div>
      </div>
      <aside className={panel}><div className="flex items-center justify-between gap-3"><div><h2 className="text-sm font-bold">AI 엔진별 결과</h2><p className="mt-1 text-[10px] text-[#8f8b98]">사용할 엔진·측정 조건 확인 필요</p></div><Bot className="size-5 text-[#6957e8]" /></div><div className="mt-5 space-y-5">{['ChatGPT 검색', 'Gemini', 'Perplexity'].map(model => <div key={model}><div className="flex items-center justify-between gap-3 text-[11px]"><span className="font-semibold">{model}</span><span className="font-bold text-[#8f8b98]">미측정</span></div><div className="mt-2 h-1.5 rounded-full bg-[#efedf4]" /><div className="mt-2 flex items-center justify-between text-[9px] text-[#96929e]"><span>공식 인용 —</span><span>답변 미수집</span></div></div>)}</div><div className="mt-6 rounded-xl bg-[#f7f5ff] p-4"><div className="text-[10px] font-bold text-[#5d49d2]">검색 실적과 구분합니다</div><p className="mt-2 text-[9px] leading-4 text-[#777381]">Search Console 자료만으로 다른 AI 서비스의 언급·인용률을 계산하지 않습니다.</p></div></aside>
    </section>
    <section className="grid gap-4 xl:grid-cols-2">
      <div className={panel}><div className="flex items-center justify-between gap-3"><div><h2 className="text-sm font-bold">콘텐츠 발행 전·후 비교</h2><p className="mt-1 text-[10px] text-[#8f8b98]">실제 게시 URL과 게시 전·후의 동일 조건 자료가 필요합니다.</p></div><Badge className="bg-[#fff3df] text-[8px] text-[#9b641f]">발행 확인 전</Badge></div><div className="mt-5 flex h-[230px] flex-col items-center justify-center rounded-xl bg-[#faf9fc] text-center"><FileCheck2 className="size-8 text-[#b1a7dd]" /><p className="mt-3 text-sm font-semibold">아직 개선율을 계산할 수 없습니다</p><p className="mt-2 text-xs text-[#8f8b98]">발행 계획 저장은 홈페이지 게시 완료가 아닙니다.</p></div><Button className="mt-4 w-full" variant="outline" onClick={() => onNavigate('studio')}>콘텐츠 준비·발행 계획 보기</Button></div>
      <div className={panel}><Ga4Performance data={ga4} onSettings={() => onNavigate('settings')} /></div>
    </section>
    <section className={`mt-5 ${panel}`}><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-bold">확보한 실제 Google 검색 자료</h2><p className="mt-1 text-[10px] leading-5 text-[#8f8b98]">{ready ? `${report.startDate} ~ ${report.endDate} · 가져온 ${report.rows.length.toLocaleString()}행 범위 · 날짜별 추이 파일은 아님` : '서치콘솔 분석에서 자료를 확인해 주세요.'}</p></div><Button size="sm" variant="outline" onClick={() => onNavigate('search-console')}><Search className="size-3.5" />원본 자료 보기</Button></div>{ready ? <><div className="my-5 grid grid-cols-3 gap-3">{[['클릭', metrics.clicks.toLocaleString()], ['노출', metrics.impressions.toLocaleString()], ['클릭률', `${metrics.ctr.toFixed(2)}%`]].map(([label, value]) => <div key={label} className="rounded-xl bg-[#f7f5ff] p-4"><div className="text-xs text-[#777381]">{label}</div><strong className="mt-2 block text-xl text-[#5d49d2]">{value}</strong></div>)}</div><div className="space-y-4">{top.map(row => <div key={row.label}><div className="mb-2 flex justify-between gap-3 text-xs"><span className="min-w-0 break-all">{row.label}</span><span className="shrink-0 font-semibold">{row.clicks.toLocaleString()}회</span></div><div className="h-1.5 rounded-full bg-[#efedf4]"><div className="h-full rounded-full bg-[#6957e8]" style={{ width: `${row.clicks / maxClicks * 100}%` }} /></div></div>)}</div></> : <p className="py-8 text-sm text-[#777381]">{loading ? '저장 자료 확인 중…' : error || '저장 자료가 없습니다.'}</p>}<p className="mt-5 text-[10px] leading-5 text-[#8f8b98]">검색어·페이지 행의 합계는 Search Console 전체 실적과 다를 수 있습니다. 현재 홈페이지 점검일과 검색 자료의 조회 기간도 서로 다릅니다.</p></section>
    <div className="mt-5 grid gap-3 md:grid-cols-3">{[['같은 조건으로 비교', '질문·모델·지역·기간이 달라지면 비교 기준을 분리합니다.', RefreshCw], ['발행 전 기준선 필수', '과거 측정값이 없으면 현재부터 수집합니다.', CalendarDays], ['숫자마다 원본 증거', '공개 웹 관찰·검색 자료·AI 답변을 각각 확인합니다.', FileCheck2]].map(([title, description, Icon]) => { const ItemIcon = Icon as typeof Bot; return <div key={String(title)} className="rounded-xl border border-[#e8e6ee] bg-white p-4"><div className="flex items-center gap-2"><ItemIcon className="size-4 text-[#6957e8]" /><h3 className="text-[11px] font-bold">{String(title)}</h3></div><p className="mt-2 text-[9px] leading-4 text-[#777381]">{String(description)}</p></div>; })}</div>
  </>;
}
